api/urls.py
from django.conf.urls import patterns, include, url

from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'participante', participante_view_set)
router.register(r'universidad', universidad_view_set)

urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    #url(r'^assdasd/$', 'existe_dni_view', name='existe_dni_url'),
    # url(r'^asistencia/(\d+)/(\d+)/$', 'asistencia_registro_view', name='asistencia_registro_url'),
)

app/models.py
# -*- coding: utf-8 -*-

from django.db import models

class slink(models.Model):
    keyword = models.CharField(max_length=140)
    def __unicode__(self): return "%s" % (self.nombre)

    class Meta:
        verbose_name = ('universidad')
        verbose_name_plural = ('universidades')

class cargo(models.Model):
    nombre = models.CharField(max_length=60)
    def __unicode__(self): return "%s" % (self.nombre)

class grado(models.Model):
    nombre = models.CharField(max_length=60)
    def __unicode__(self): return "%s" % (self.nombre)

class participante(models.Model):
    dni = models.CharField(max_length=8, primary_key=True, verbose_name="DNI")
    paterno = models.CharField(max_length=80, verbose_name="Apellido Paterno")
    materno = models.CharField(max_length=80, verbose_name="Apellido Materno")
    nombre = models.CharField(max_length=100, verbose_name="Nombre(s)")
    edad = models.SmallIntegerField(verbose_name="Edad", blank=True)
    direccion = models.CharField(max_length=140, verbose_name="Dirección")
    email = models.EmailField(verbose_name="Email")
    fijo = models.CharField(max_length=12, verbose_name="Teléfono Fijo",blank=True)
    movil = models.CharField(max_length=12, verbose_name="Teléfono Movil",blank=True)
    universidad = models.ForeignKey(universidad, verbose_name="Universidad")
    facultad = models.CharField(max_length=140, verbose_name="Facultad")
    carrera = models.CharField(max_length=140, verbose_name="Carrera")
    titulo = models.CharField(max_length=140, verbose_name="Título",blank=True)
    cargo = models.ForeignKey(cargo, verbose_name="Cargo")
    grado = models.ForeignKey(grado, verbose_name="Grado")
    investigacion = models.TextField(verbose_name="Trabajos de Investigación", blank=True)
    ingreso = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return u"(%s) %s-%s-%s" % (self.dni, self.paterno, self.materno, self.nombre)

    def save(self):
        self.paterno = self.paterno.upper()
        self.materno = self.materno.upper()
        self.nombre = self.nombre.upper()
        self.direccion = self.direccion.upper()
        self.email = self.email.lower()
        self.facultad = self.facultad.upper()
        self.carrera = self.carrera.upper()
        self.titulo = self.titulo.upper()
        if self.edad is None: self.edad = 0
        super(participante, self).save()

class evento(models.Model):
    nombre = models.CharField(max_length=60)
    cerrado = models.BooleanField(default=False)
    fecha_hora = models.DateTimeField()
    def __unicode__(self): return "%s" % (self.nombre)

class asistencia(models.Model):
    evento = models.ForeignKey(evento, verbose_name='Evento')
    participante  = models.ForeignKey(participante, verbose_name='Participante')
    fecha_hora = models.DateTimeField(auto_now=True)
    def __unicode__(self): return u"%s - %s" % (self.evento, self.participante)

    class Meta:
        unique_together = ('evento', 'participante',)

app/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core.validators import (MaxLengthValidator, MinLengthValidator, RegexValidator,
    MinValueValidator, MaxValueValidator, validate_email)

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Button, Fieldset
from crispy_forms.bootstrap import PrependedText, PrependedAppendedText, FormActions

from .models import participante, asistencia, evento


class participante_crear_form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(participante_crear_form, self).__init__(*args, **kwargs)
        self.fields["dni"].validators.append(MinLengthValidator(8))
        self.fields["dni"].validators.append(RegexValidator(regex="^[0-9]+$"))
        self.fields["edad"].validators.append(MinValueValidator(12))
        self.fields["edad"].validators.append(MaxValueValidator(128))
        self.fields["edad"].required=False
        self.fields["email"].validators.append(validate_email)
        self.fields["fijo"].validators.append(RegexValidator(regex="^[0-9]+$"))
        self.fields["fijo"].required=False
        self.fields["movil"].validators.append(RegexValidator(regex="^[0-9]+$"))
        self.fields["movil"].required=False
        self.fields["titulo"].required=False
        self.fields["investigacion"].required=False

        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'

        self.helper.layout = Layout(
            Fieldset(u'<span class="glyphicon glyphicon-pencil"></span> Formato de Inscripción',
                PrependedText('dni', '#'),
                'paterno',
                'materno',
                'nombre',
                PrependedText('edad', '#'),
                'direccion',
                PrependedText('email', '@'),
                PrependedText('fijo', '#'),
                PrependedText('movil', '#'),
                'universidad',
                'facultad',
                'carrera',
                'titulo',
                'cargo',
                'grado',
                'investigacion',
            ),
            FormActions(
                Submit('submit', u'Inscripción'),
                css_class='text-right'
            ),
        )

    class Meta:
        model = participante
        exclude = ()


class participante_constancia_form(forms.Form):
    dni = forms.CharField(label='DNI', max_length=8)
    dni.validators.append(MinLengthValidator(1))
    dni.validators.append(MaxLengthValidator(8))
    dni.validators.append(RegexValidator(regex="^[0-9]+$"))
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    helper.label_class = 'col-md-3'
    helper.field_class = 'col-md-9'
    helper.layout = Layout(
        Fieldset(u'<span class="glyphicon glyphicon-pencil"></span> Reporte Constancia',
                PrependedText('dni', '#'),
        ),

        FormActions(
            Submit('submit', u'Constancia'),
            css_class='text-right'
        ),
    )

    def clean_dni(self):
        item = self.cleaned_data['dni']
        try:
            inscrito = participante.objects.get(dni=item)
        except:
            raise forms.ValidationError(u'DNI no esta registrado.')
        return item

class asistencia_form(forms.ModelForm):
    dni = forms.CharField(required=True, )

    def __init__(self, *args, **kwargs):
        super(asistencia_form, self).__init__(*args, **kwargs)
        self.fields['evento'].queryset = evento.objects.filter(cerrado=False)
        self.fields['dni'].widget.attrs['minlength'] = '8'
        self.fields['dni'].widget.attrs['maxlength'] = '8'
        self.fields['dni'].widget.attrs['autocomplete'] = 'off'
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'

        self.helper.layout = Layout(
            'evento',
            PrependedText('dni', '#'),
        )

    class Meta:
        model = asistencia
        exclude = ()

templates/asistencia/asistencia.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Asistencia{% endblock %}
{% block content %}
<h3><span class="glyphicon glyphicon-search"></span> Control Asistencia</h3>
<div class="well bs-component">
    {% crispy form %}
    <p id="mensaje"></p>
</div>
<p class="text-danger" id="pendientes"></p>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            simg = '<img src="/static/img/loading.gif" alt="Cargando" id="simg" />';

            $(window).keydown(function(event){
                if( (event.keyCode == 13) ) {
                    event.preventDefault();
                    return false;
                }
            });

            $('#id_dni').keyup(function () {
                dni = $('#id_dni').val()
                if ( $('#id_dni').val().length == 8 && !$("#id_dni").prop("readonly") ) {
                    if ($("#id_evento").val() == '') {
                        alert('Seleccione evento.');
                        $('#id_dni').val('');
                        return false;
                    }

                    $("#id_dni").prop("readonly",true);
                    $('#mensaje').empty();
                    $('#mensaje').after(simg);

                    evento = $('#id_evento').val()
                    $.ajax({
                        url: '/asistencia/' + evento + '/' + dni + '/',
                        timeout: 5000,
                    })
                    .done(function(response) {
                        $('#simg').remove();
                        $('#mensaje').append(response);
                    })
                    .fail(function() {
                        $('#simg').remove();
                        $('#mensaje').append('¡Error de conexión ó DNI no está registrado!, agregado lista de pendientes.<br>');
                        $('#pendientes').append('<small>' + dni + '</small><br>');
                    })
                     .always(function() {
                        $('#id_dni').val('')
                        $("#id_dni").prop("readonly",false);
                        $("#id_dni").focus();
                    });
                }
            });

        });
    </script>

{% endblock %}